//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain
{
    using System;
    using System.Collections.Generic;

    [Table("Color")]
    public partial class Color : Entity
    {
        public Color()
        {
            this.FurnitureModels = new HashSet<FurnitureModel>();
        }
    
        public int ColorId { get; set; }

        [Column("Color")]
        public string ColorName { get; set; }
    
        public virtual ICollection<FurnitureModel> FurnitureModels { get; set; }
    }
}
