//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    [Table("FurnitureModel")]
    public partial class FurnitureModel : Entity
    {
        public FurnitureModel()
        {
            this.Products = new HashSet<Product>();
            this.Colors = new HashSet<Color>();
            this.Materials = new HashSet<Material>();
        }
    
        [Key]
        public int FurnitureModelId { get; set; }
        public string Name { get; set; }
        public string AdditionalInfo { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> RoomId { get; set; }
    
        public virtual FurnitureType FurnitureType { get; set; }
        public virtual Room Room { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<Color> Colors { get; set; }
        public virtual ICollection<Material> Materials { get; set; }
    }
}
