//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    [Table("FurnitureType")]
    public partial class FurnitureType : BaseEntity
    {
        public FurnitureType()
        {
            this.FurnitureModel = new HashSet<FurnitureModel>();
        }
    
        [Key]
        public int TypeId { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<FurnitureModel> FurnitureModel { get; set; }
    }
}
