//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    [Table("Product")]
    public partial class Product : BaseEntity
    {
        public Product()
        {
            this.Sale = new HashSet<Sale>();
        }
        
        [Key]
        public int ProductId { get; set; }
        public string SerialNumber { get; set; }
        public int StatusId { get; set; }
        public int FurnitureModelId { get; set; }
        public System.DateTime AssemblyDate { get; set; }
    
        public virtual FurnitureModel FurnitureModel { get; set; }
        public virtual ProductStatus ProductStatus { get; set; }
        public virtual ICollection<Sale> Sale { get; set; }
    }
}
