//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    [Table("ProductStatus")]
    public partial class ProductStatus : BaseEntity
    {
        public ProductStatus()
        {
            this.Product = new HashSet<Product>();
        }
    
        [Key]
        public int StatusId { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<Product> Product { get; set; }
    }
}
