//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    [Table("Sale")]
    public partial class Sale : BaseEntity
    {
        [Key]
        public int SaleId { get; set; }
        public int ProductId { get; set; }
        public System.DateTime SaleDate { get; set; }
        public double Cost { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
