//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    [Table("Warehouse")]
    public partial class Warehouse : Entity
    {
        [Key, ForeignKey("Product")]
        public int ProductId { get; set; }
        public Nullable<DateTime> UpdateDate { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
